export const Name = 'Inferno'
export const Tagline = '17th International Annual Conference on Comedy and Knowledge'
export const Description = 'Inferno is a fictional event where world\'s best minds and world\'s best comedians come together to have fun and share knowledge. Register now to enjoy a day full of laughter and knowledge'
export const Time = '8:00 am on 22nd September 2021'
export const Venue = 'Delhi, India'
