export const Name = 'Event'
export const Tagline = 'Event Tagline'
export const Description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
export const Time = '17:30 hrs on 32nd September 3021'
export const Venue = 'Pluto'