export const Name = 'Confluence 2021'
export const Tagline = '11th IEEE International Conference on Cloud Computing, Data Science and Engineering'
export const Description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
export const Time = '8:00 am on 32nd September 3021'
export const Venue = 'Pluto'
